# Generated by Django 4.2 on 2024-08-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title_new',
        ),
    ]
